application:
  build: application
  links:
    - mysql
    - mongo
    - elasticsearch
    - redis
    - rabbitmq
  volumes:
    - ./web:/var/www
  environment:
    TERM: xterm

mysql:
  image: tutum/mysql
  expose:
    - "3306"
  environment:
    MYSQL_USER: "root"
    MYSQL_PASS: "root"

mongo:
  image: mongo
  expose:
    - "27017"

elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"

redis:
  image: redis

rabbitmq:
  image: rabbitmq
